name: Feature Request
description: Propose a new feature
title: "[Feature]: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please describe the feature you'd like to see implemented
      placeholder: What would you like to see added?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Do you have any ideas about how this feature could be implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What criteria should be met for this feature to be considered complete?
      placeholder: |
        1. Should be able to...
        2. Must include...
        3. When user does X, Y should happen
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, use cases, or screenshots about the feature request
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have technical details about the implementation, please share them
